import "server-only";
import indexFile from "../../fixtures/qloo/index.json";
import f0 from "../../fixtures/qloo/fx-p1-book-wide.json";
import f1 from "../../fixtures/qloo/fx-p1-book.json";
import f2 from "../../fixtures/qloo/fx-p1-brand.json";
import f3 from "../../fixtures/qloo/fx-p1-film-wide.json";
import f4 from "../../fixtures/qloo/fx-p1-film.json";
import f5 from "../../fixtures/qloo/fx-p1-music.json";
import f6 from "../../fixtures/qloo/fx-p1-place.json";
import f7 from "../../fixtures/qloo/fx-p1-tags.json";
import f8 from "../../fixtures/qloo/fx-p1-tv-wide.json";
import f9 from "../../fixtures/qloo/fx-p1-tv.json";
import f10 from "../../fixtures/qloo/fx-p2-book-wide.json";
import f11 from "../../fixtures/qloo/fx-p2-book.json";
import f12 from "../../fixtures/qloo/fx-p2-brand.json";
import f13 from "../../fixtures/qloo/fx-p2-film-wide.json";
import f14 from "../../fixtures/qloo/fx-p2-film.json";
import f15 from "../../fixtures/qloo/fx-p2-music.json";
import f16 from "../../fixtures/qloo/fx-p2-place.json";
import f17 from "../../fixtures/qloo/fx-p2-tags.json";
import f18 from "../../fixtures/qloo/fx-p2-tv-wide.json";
import f19 from "../../fixtures/qloo/fx-p2-tv.json";
import f20 from "../../fixtures/qloo/fx-p3-book-wide.json";
import f21 from "../../fixtures/qloo/fx-p3-book.json";
import f22 from "../../fixtures/qloo/fx-p3-brand.json";
import f23 from "../../fixtures/qloo/fx-p3-film-wide.json";
import f24 from "../../fixtures/qloo/fx-p3-film.json";
import f25 from "../../fixtures/qloo/fx-p3-music.json";
import f26 from "../../fixtures/qloo/fx-p3-place.json";
import f27 from "../../fixtures/qloo/fx-p3-tags.json";
import f28 from "../../fixtures/qloo/fx-p3-tv-wide.json";
import f29 from "../../fixtures/qloo/fx-p3-tv.json";
import f30 from "../../fixtures/qloo/fx-p4-book-wide.json";
import f31 from "../../fixtures/qloo/fx-p4-book.json";
import f32 from "../../fixtures/qloo/fx-p4-brand.json";
import f33 from "../../fixtures/qloo/fx-p4-film-wide.json";
import f34 from "../../fixtures/qloo/fx-p4-film.json";
import f35 from "../../fixtures/qloo/fx-p4-music.json";
import f36 from "../../fixtures/qloo/fx-p4-place.json";
import f37 from "../../fixtures/qloo/fx-p4-tags.json";
import f38 from "../../fixtures/qloo/fx-p4-tv-wide.json";
import f39 from "../../fixtures/qloo/fx-p4-tv.json";
import f40 from "../../fixtures/qloo/fx-p5-book-wide.json";
import f41 from "../../fixtures/qloo/fx-p5-book.json";
import f42 from "../../fixtures/qloo/fx-p5-brand.json";
import f43 from "../../fixtures/qloo/fx-p5-film-wide.json";
import f44 from "../../fixtures/qloo/fx-p5-film.json";
import f45 from "../../fixtures/qloo/fx-p5-music.json";
import f46 from "../../fixtures/qloo/fx-p5-place.json";
import f47 from "../../fixtures/qloo/fx-p5-tags.json";
import f48 from "../../fixtures/qloo/fx-p5-tv-wide.json";
import f49 from "../../fixtures/qloo/fx-p5-tv.json";
import f50 from "../../fixtures/qloo/fx-search.json";
import f51 from "../../fixtures/qloo/fx-tags.json";
import { loadFixtureIndex } from "./fixtureIndex";

/**
 * GENERATED by `pnpm fixtures:build` from `scripts/qloo-fixtures/`: do not edit.
 * The hand-made `fx-` fixtures, bundled statically so they travel with the
 * server build on any host (no runtime file-system access).
 */
export const bundledFixtureIndex = loadFixtureIndex(indexFile, {
  "fx-p1-book-wide.json": f0,
  "fx-p1-book.json": f1,
  "fx-p1-brand.json": f2,
  "fx-p1-film-wide.json": f3,
  "fx-p1-film.json": f4,
  "fx-p1-music.json": f5,
  "fx-p1-place.json": f6,
  "fx-p1-tags.json": f7,
  "fx-p1-tv-wide.json": f8,
  "fx-p1-tv.json": f9,
  "fx-p2-book-wide.json": f10,
  "fx-p2-book.json": f11,
  "fx-p2-brand.json": f12,
  "fx-p2-film-wide.json": f13,
  "fx-p2-film.json": f14,
  "fx-p2-music.json": f15,
  "fx-p2-place.json": f16,
  "fx-p2-tags.json": f17,
  "fx-p2-tv-wide.json": f18,
  "fx-p2-tv.json": f19,
  "fx-p3-book-wide.json": f20,
  "fx-p3-book.json": f21,
  "fx-p3-brand.json": f22,
  "fx-p3-film-wide.json": f23,
  "fx-p3-film.json": f24,
  "fx-p3-music.json": f25,
  "fx-p3-place.json": f26,
  "fx-p3-tags.json": f27,
  "fx-p3-tv-wide.json": f28,
  "fx-p3-tv.json": f29,
  "fx-p4-book-wide.json": f30,
  "fx-p4-book.json": f31,
  "fx-p4-brand.json": f32,
  "fx-p4-film-wide.json": f33,
  "fx-p4-film.json": f34,
  "fx-p4-music.json": f35,
  "fx-p4-place.json": f36,
  "fx-p4-tags.json": f37,
  "fx-p4-tv-wide.json": f38,
  "fx-p4-tv.json": f39,
  "fx-p5-book-wide.json": f40,
  "fx-p5-book.json": f41,
  "fx-p5-brand.json": f42,
  "fx-p5-film-wide.json": f43,
  "fx-p5-film.json": f44,
  "fx-p5-music.json": f45,
  "fx-p5-place.json": f46,
  "fx-p5-tags.json": f47,
  "fx-p5-tv-wide.json": f48,
  "fx-p5-tv.json": f49,
  "fx-search.json": f50,
  "fx-tags.json": f51,
});
